### ISSUE TITLE
WSL broken with 4.1.6

### ISSUE THREAD

**Issue by TheStu** [SublimeLinter/SublimeLinter-eslint#275]
I have eslint installed in WSL and Sublime installed on Windows, using a bat file to communicate between the two (https://github.com/Microsoft/vscode-eslint/issues/251#issuecomment-418240188).

With the update to 4.1.6 something has gone wrong with that setup.

4.1.6 Sublime console:
```
DPI mode: per-monitor v2
startup, version: 3207 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/stuwa/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/stuwa/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/stuwa/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.15938
startup time: 0.21238
first paint time: 0.21338
git: tracking working dir C:\rails\tcg-website
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin 1Self.1self
reloading plugin 1Self.1selfOpenDashboardCommand
reloading plugin All Autocomplete.all_views_completions
reloading plugin Emmet.emmet-plugin
reloading plugin GitGutter.plugin
reloading plugin Materialize.Materialize
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SCSS.scss_completions
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-rubocop.linter
reloading plugin SublimeLinter-ruby.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin Babel.Babel
plugins loaded
Initializing 1self plugin
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 298, in on_api_ready
    plc()
  File "C:\Users\stuwa\AppData\Roaming\Sublime Text 3\Installed Packages\1Self.sublime-package\1self.py", line 58, in plugin_loaded
    after_loaded()
  File "C:\Users\stuwa\AppData\Roaming\Sublime Text 3\Installed Packages\1Self.sublime-package\1self.py", line 65, in after_loaded
    get_stream_id_if_not_present()
  File "C:\Users\stuwa\AppData\Roaming\Sublime Text 3\Installed Packages\1Self.sublime-package\1self.py", line 135, in get_stream_id_if_not_present
    response = urllib2.urlopen(req)
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 475, in open
  File "./python3.3/urllib/request.py", line 587, in http_response
  File "./python3.3/urllib/request.py", line 513, in error
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 595, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:50   debug mode: on
SublimeLinter: sublime_linter.py:51   version: 4.10.0
SublimeLinter: sublime_linter.py:253  Delay linting 'server.js' for 0.0s
SublimeLinter: linter.py:970          eslint: checking lint mode 'background' vs lint reason 'on_load'
SublimeLinter: #1 linter.py:987       eslint: linting 'server.js'
SublimeLinter: #1 linter.py:778       eslint: wanted executable is 'C:\rails\eslint.bat'
SublimeLinter: #1 linter.py:1462      Running ...

  C:\rails\tcg-website  (working dir)
  > type server.js | C:\rails\eslint.bat --format json --stdin --stdin-filename C:\rails\tcg-website\server.js

Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2019-04-12 10:37:50, next run at 2019-04-12 11:37:50 or after
SublimeLinter: #1 linter.py:1066      eslint: output:
  [{"filePath":"/mnt/c/rails/tcg-website/C:railstcg-websiteserver.js","messages":[{"ruleId":"import/newline-after-import","severity":2,"message":"Expected 1 empty line after require statement not followed by another require.","line":3,"column":1,"nodeType":null,"fix":{"range":[117,117],"text":"\n"}},{"ruleId":"func-names","severity":1,"message":"Unexpected unnamed function.","line":32,"column":17,"nodeType":"FunctionExpression","messageId":"unnamed","endLine":39,"endColumn":2},{"ruleId":"prefer-arrow-callback","severity":2,"message":"Unexpected function expression.","line":32,"column":17,"nodeType":"FunctionExpression","endLine":39,"endColumn":2,"fix":{"range":[804,960],"text":"(req, res, next) => {\n  req.url = req.url + '.gz';\n  res.set({\n    'Content-Encoding': 'gzip',\n    'Content-Type': 'text/javascript'\n  });\n  next();\n}"}},{"ruleId":"operator-assignment","severity":2,"message":"Assignment can be replaced with operator assignment.","line":33,"column":3,"nodeType":"AssignmentExpression","endLine":33,"endColumn":28,"fix":{"range":[834,859],"text":"req.url += '.gz'"}},{"ruleId":"prefer-template","severity":2,"message":"Unexpected string concatenation.","line":33,"column":13,"nodeType":"BinaryExpression","endLine":33,"endColumn":28,"fix":{"range":[844,859],"text":"`${req.url  }.gz`"}},{"ruleId":"comma-dangle","severity":2,"message":"Missing trailing comma.","line":36,"column":38,"nodeType":"Property","messageId":"missing","fix":{"range":[942,942],"text":","}}],"errorCount":5,"warningCount":1,"fixableErrorCount":5,"fixableWarningCount":0,"source":"const path = require('path');\nconst sslRedirect = require('heroku-ssl-redirect');\nconst express = require('express');\nconst app = express();\n\napp.use(sslRedirect());\napp.use(require('prerender-node').set('prerenderToken', 'UQ05eu1qKxhBgrHTDFCr').whitelisted([\n  '^/$', // root url\n  '/about(#.*)?',\n  '/courses$',\n  '/courses/\\\\d*/.*',\n  '/daily-videos/\\\\d*/.*',\n  '/privacy$',\n  '/contact$',\n  '/membership$',\n  '/users/sign_up$',\n  '/users/sign_in$',\n  '/users/password/forgot$',\n  '/affiliates/sign_up$',\n  '/affiliates/sign_in$',\n  '/affiliates/password/forgot$',\n  '/app/user-dashboard$',\n  '/app/live-market-analysis$',\n  '/app/whiteboard$',\n  '/app/daily-videos$',\n  '/app/educational-videos$',\n  '/app/broadcast-archives$',\n  '/app/courses/\\\\d*',\n  '/app/course-unit/\\\\d*',\n]));\n\napp.get('*.js', function (req, res, next) {\n  req.url = req.url + '.gz';\n  res.set({\n    'Content-Encoding': 'gzip',\n    'Content-Type': 'text/javascript'\n  });\n  next();\n});\n\napp.use(express.static(path.join(__dirname, 'build')));\n\napp.use('*', (req, res) => {\n  res.sendFile(path.join(__dirname, 'build/index.html'));\n});\n\napp.listen(process.env.PORT || 8080);\n"}]
SublimeLinter: #1 linter.py:73        eslint output:
[{'errorCount': 5,
  'filePath': '/mnt/c/rails/tcg-website/C:railstcg-websiteserver.js',
  'fixableErrorCount': 5,
  'fixableWarningCount': 0,
  'messages': [{'column': 1,
                'fix': {'range': [117, 117], 'text': '\n'},
                'line': 3,
                'message': 'Expected 1 empty line after require statement not followed by another require.',
                'nodeType': None,
                'ruleId': 'import/newline-after-import',
                'severity': 2},
               {'column': 17,
                'endColumn': 2,
                'endLine': 39,
                'line': 32,
                'message': 'Unexpected unnamed function.',
                'messageId': 'unnamed',
                'nodeType': 'FunctionExpression',
                'ruleId': 'func-names',
                'severity': 1},
               {'column': 17,
                'endColumn': 2,
                'endLine': 39,
                'fix': {'range': [804, 960],
                        'text': "(req, res, next) => {\n  req.url = req.url + '.gz';\n  res.set({\n    'Content-Encoding': 'gzip',\n    'Content-Type': 'text/javascript'\n  });\n  next();\n}"},
                'line': 32,
                'message': 'Unexpected function expression.',
                'nodeType': 'FunctionExpression',
                'ruleId': 'prefer-arrow-callback',
                'severity': 2},
               {'column': 3,
                'endColumn': 28,
                'endLine': 33,
                'fix': {'range': [834, 859], 'text': "req.url += '.gz'"},
                'line': 33,
                'message': 'Assignment can be replaced with operator assignment.',
                'nodeType': 'AssignmentExpression',
                'ruleId': 'operator-assignment',
                'severity': 2},
               {'column': 13,
                'endColumn': 28,
                'endLine': 33,
                'fix': {'range': [844, 859], 'text': '`${req.url  }.gz`'},
                'line': 33,
                'message': 'Unexpected string concatenation.',
                'nodeType': 'BinaryExpression',
                'ruleId': 'prefer-template',
                'severity': 2},
               {'column': 38,
                'fix': {'range': [942, 942], 'text': ','},
                'line': 36,
                'message': 'Missing trailing comma.',
                'messageId': 'missing',
                'nodeType': 'Property',
                'ruleId': 'comma-dangle',
                'severity': 2}],
  'source': "const path = require('path');\nconst sslRedirect = require('heroku-ssl-redirect');\nconst express = require('express');\nconst app = express();\n\napp.use(sslRedirect());\napp.use(require('prerender-node').set('prerenderToken', 'UQ05eu1qKxhBgrHTDFCr').whitelisted([\n  '^/$', // root url\n  '/about(#.*)?',\n  '/courses$',\n  '/courses/\\\\d*/.*',\n  '/daily-videos/\\\\d*/.*',\n  '/privacy$',\n  '/contact$',\n  '/membership$',\n  '/users/sign_up$',\n  '/users/sign_in$',\n  '/users/password/forgot$',\n  '/affiliates/sign_up$',\n  '/affiliates/sign_in$',\n  '/affiliates/password/forgot$',\n  '/app/user-dashboard$',\n  '/app/live-market-analysis$',\n  '/app/whiteboard$',\n  '/app/daily-videos$',\n  '/app/educational-videos$',\n  '/app/broadcast-archives$',\n  '/app/courses/\\\\d*',\n  '/app/course-unit/\\\\d*',\n]));\n\napp.get('*.js', function (req, res, next) {\n  req.url = req.url + '.gz';\n  res.set({\n    'Content-Encoding': 'gzip',\n    'Content-Type': 'text/javascript'\n  });\n  next();\n});\n\napp.use(express.static(path.join(__dirname, 'build')));\n\napp.use('*', (req, res) => {\n  res.sendFile(path.join(__dirname, 'build/index.html'));\n});\n\napp.listen(process.env.PORT || 8080);\n",
  'warningCount': 1}]
SublimeLinter: #1 linter.py:1171      WARNING: eslint reported errors coming from 'C:\mnt\c\rails\tcg-website\C:railstcg-websiteserver.js'. However, reading that file raised:
  [Errno 2] No such file or directory: 'C:\\mnt\\c\\rails\\tcg-website\\C:railstcg-websiteserver.js'.
SublimeLinter: #1 linter.py:1171      WARNING: eslint reported errors coming from 'C:\mnt\c\rails\tcg-website\C:railstcg-websiteserver.js'. However, reading that file raised:
  [Errno 2] No such file or directory: 'C:\\mnt\\c\\rails\\tcg-website\\C:railstcg-websiteserver.js'.
SublimeLinter: #1 linter.py:1171      WARNING: eslint reported errors coming from 'C:\mnt\c\rails\tcg-website\C:railstcg-websiteserver.js'. However, reading that file raised:
  [Errno 2] No such file or directory: 'C:\\mnt\\c\\rails\\tcg-website\\C:railstcg-websiteserver.js'.
SublimeLinter: #1 linter.py:1171      WARNING: eslint reported errors coming from 'C:\mnt\c\rails\tcg-website\C:railstcg-websiteserver.js'. However, reading that file raised:
  [Errno 2] No such file or directory: 'C:\\mnt\\c\\rails\\tcg-website\\C:railstcg-websiteserver.js'.
SublimeLinter: #1 linter.py:1171      WARNING: eslint reported errors coming from 'C:\mnt\c\rails\tcg-website\C:railstcg-websiteserver.js'. However, reading that file raised:
  [Errno 2] No such file or directory: 'C:\\mnt\\c\\rails\\tcg-website\\C:railstcg-websiteserver.js'.
SublimeLinter: #1 linter.py:1171      WARNING: eslint reported errors coming from 'C:\mnt\c\rails\tcg-website\C:railstcg-websiteserver.js'. However, reading that file raised:
  [Errno 2] No such file or directory: 'C:\\mnt\\c\\rails\\tcg-website\\C:railstcg-websiteserver.js'.
SublimeLinter: sublime_linter.py:507  Linting 'server.js' took 5.28s
```

4.1.5 Sublime console:
```
DPI mode: per-monitor v2
startup, version: 3207 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/stuwa/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/stuwa/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/stuwa/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.239782
startup time: 0.309782
first paint time: 0.312782
git: tracking working dir C:\rails\tcg-website
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin 1Self.1self
reloading plugin 1Self.1selfOpenDashboardCommand
reloading plugin All Autocomplete.all_views_completions
reloading plugin Emmet.emmet-plugin
reloading plugin GitGutter.plugin
reloading plugin Materialize.Materialize
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SCSS.scss_completions
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-rubocop.linter
reloading plugin SublimeLinter-ruby.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin Babel.Babel
plugins loaded
Initializing 1self plugin
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 298, in on_api_ready
    plc()
  File "C:\Users\stuwa\AppData\Roaming\Sublime Text 3\Installed Packages\1Self.sublime-package\1self.py", line 58, in plugin_loaded
    after_loaded()
  File "C:\Users\stuwa\AppData\Roaming\Sublime Text 3\Installed Packages\1Self.sublime-package\1self.py", line 65, in after_loaded
    get_stream_id_if_not_present()
  File "C:\Users\stuwa\AppData\Roaming\Sublime Text 3\Installed Packages\1Self.sublime-package\1self.py", line 135, in get_stream_id_if_not_present
    response = urllib2.urlopen(req)
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 475, in open
  File "./python3.3/urllib/request.py", line 587, in http_response
  File "./python3.3/urllib/request.py", line 513, in error
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 595, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:50   debug mode: on
SublimeLinter: sublime_linter.py:51   version: 4.10.0
SublimeLinter: sublime_linter.py:253  Delay linting '<untitled 28>' for 0.0s
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2019-04-12 10:37:50, next run at 2019-04-12 11:37:50 or after
SublimeLinter: sublime_linter.py:253  Delay linting 'server.js' for 0.0s
SublimeLinter: linter.py:970          eslint: checking lint mode 'background' vs lint reason 'on_load'
SublimeLinter: #1 linter.py:987       eslint: linting 'server.js'
SublimeLinter: #1 linter.py:778       eslint: wanted executable is 'C:\rails\eslint.bat'
SublimeLinter: #1 linter.py:1462      Running ...

  C:\rails\tcg-website  (working dir)
  > type server.js | C:\rails\eslint.bat --format json --stdin --stdin-filename C:\rails\tcg-website\server.js

SublimeLinter: #1 linter.py:1066      eslint: output:
  [{"filePath":"/mnt/c/rails/tcg-website/C:railstcg-websiteserver.js","messages":[{"ruleId":"import/newline-after-import","severity":2,"message":"Expected 1 empty line after require statement not followed by another require.","line":3,"column":1,"nodeType":null,"fix":{"range":[117,117],"text":"\n"}},{"ruleId":"func-names","severity":1,"message":"Unexpected unnamed function.","line":32,"column":17,"nodeType":"FunctionExpression","messageId":"unnamed","endLine":39,"endColumn":2},{"ruleId":"prefer-arrow-callback","severity":2,"message":"Unexpected function expression.","line":32,"column":17,"nodeType":"FunctionExpression","endLine":39,"endColumn":2,"fix":{"range":[804,960],"text":"(req, res, next) => {\n  req.url = req.url + '.gz';\n  res.set({\n    'Content-Encoding': 'gzip',\n    'Content-Type': 'text/javascript'\n  });\n  next();\n}"}},{"ruleId":"operator-assignment","severity":2,"message":"Assignment can be replaced with operator assignment.","line":33,"column":3,"nodeType":"AssignmentExpression","endLine":33,"endColumn":28,"fix":{"range":[834,859],"text":"req.url += '.gz'"}},{"ruleId":"prefer-template","severity":2,"message":"Unexpected string concatenation.","line":33,"column":13,"nodeType":"BinaryExpression","endLine":33,"endColumn":28,"fix":{"range":[844,859],"text":"`${req.url  }.gz`"}},{"ruleId":"comma-dangle","severity":2,"message":"Missing trailing comma.","line":36,"column":38,"nodeType":"Property","messageId":"missing","fix":{"range":[942,942],"text":","}}],"errorCount":5,"warningCount":1,"fixableErrorCount":5,"fixableWarningCount":0,"source":"const path = require('path');\nconst sslRedirect = require('heroku-ssl-redirect');\nconst express = require('express');\nconst app = express();\n\napp.use(sslRedirect());\napp.use(require('prerender-node').set('prerenderToken', 'UQ05eu1qKxhBgrHTDFCr').whitelisted([\n  '^/$', // root url\n  '/about(#.*)?',\n  '/courses$',\n  '/courses/\\\\d*/.*',\n  '/daily-videos/\\\\d*/.*',\n  '/privacy$',\n  '/contact$',\n  '/membership$',\n  '/users/sign_up$',\n  '/users/sign_in$',\n  '/users/password/forgot$',\n  '/affiliates/sign_up$',\n  '/affiliates/sign_in$',\n  '/affiliates/password/forgot$',\n  '/app/user-dashboard$',\n  '/app/live-market-analysis$',\n  '/app/whiteboard$',\n  '/app/daily-videos$',\n  '/app/educational-videos$',\n  '/app/broadcast-archives$',\n  '/app/courses/\\\\d*',\n  '/app/course-unit/\\\\d*',\n]));\n\napp.get('*.js', function (req, res, next) {\n  req.url = req.url + '.gz';\n  res.set({\n    'Content-Encoding': 'gzip',\n    'Content-Type': 'text/javascript'\n  });\n  next();\n});\n\napp.use(express.static(path.join(__dirname, 'build')));\n\napp.use('*', (req, res) => {\n  res.sendFile(path.join(__dirname, 'build/index.html'));\n});\n\napp.listen(process.env.PORT || 8080);\n"}]
SublimeLinter: #1 linter.py:73        eslint output:
[{'errorCount': 5,
  'filePath': '/mnt/c/rails/tcg-website/C:railstcg-websiteserver.js',
  'fixableErrorCount': 5,
  'fixableWarningCount': 0,
  'messages': [{'column': 1,
                'fix': {'range': [117, 117], 'text': '\n'},
                'line': 3,
                'message': 'Expected 1 empty line after require statement not followed by another require.',
                'nodeType': None,
                'ruleId': 'import/newline-after-import',
                'severity': 2},
               {'column': 17,
                'endColumn': 2,
                'endLine': 39,
                'line': 32,
                'message': 'Unexpected unnamed function.',
                'messageId': 'unnamed',
                'nodeType': 'FunctionExpression',
                'ruleId': 'func-names',
                'severity': 1},
               {'column': 17,
                'endColumn': 2,
                'endLine': 39,
                'fix': {'range': [804, 960],
                        'text': "(req, res, next) => {\n  req.url = req.url + '.gz';\n  res.set({\n    'Content-Encoding': 'gzip',\n    'Content-Type': 'text/javascript'\n  });\n  next();\n}"},
                'line': 32,
                'message': 'Unexpected function expression.',
                'nodeType': 'FunctionExpression',
                'ruleId': 'prefer-arrow-callback',
                'severity': 2},
               {'column': 3,
                'endColumn': 28,
                'endLine': 33,
                'fix': {'range': [834, 859], 'text': "req.url += '.gz'"},
                'line': 33,
                'message': 'Assignment can be replaced with operator assignment.',
                'nodeType': 'AssignmentExpression',
                'ruleId': 'operator-assignment',
                'severity': 2},
               {'column': 13,
                'endColumn': 28,
                'endLine': 33,
                'fix': {'range': [844, 859], 'text': '`${req.url  }.gz`'},
                'line': 33,
                'message': 'Unexpected string concatenation.',
                'nodeType': 'BinaryExpression',
                'ruleId': 'prefer-template',
                'severity': 2},
               {'column': 38,
                'fix': {'range': [942, 942], 'text': ','},
                'line': 36,
                'message': 'Missing trailing comma.',
                'messageId': 'missing',
                'nodeType': 'Property',
                'ruleId': 'comma-dangle',
                'severity': 2}],
  'source': "const path = require('path');\nconst sslRedirect = require('heroku-ssl-redirect');\nconst express = require('express');\nconst app = express();\n\napp.use(sslRedirect());\napp.use(require('prerender-node').set('prerenderToken', 'UQ05eu1qKxhBgrHTDFCr').whitelisted([\n  '^/$', // root url\n  '/about(#.*)?',\n  '/courses$',\n  '/courses/\\\\d*/.*',\n  '/daily-videos/\\\\d*/.*',\n  '/privacy$',\n  '/contact$',\n  '/membership$',\n  '/users/sign_up$',\n  '/users/sign_in$',\n  '/users/password/forgot$',\n  '/affiliates/sign_up$',\n  '/affiliates/sign_in$',\n  '/affiliates/password/forgot$',\n  '/app/user-dashboard$',\n  '/app/live-market-analysis$',\n  '/app/whiteboard$',\n  '/app/daily-videos$',\n  '/app/educational-videos$',\n  '/app/broadcast-archives$',\n  '/app/courses/\\\\d*',\n  '/app/course-unit/\\\\d*',\n]));\n\napp.get('*.js', function (req, res, next) {\n  req.url = req.url + '.gz';\n  res.set({\n    'Content-Encoding': 'gzip',\n    'Content-Type': 'text/javascript'\n  });\n  next();\n});\n\napp.use(express.static(path.join(__dirname, 'build')));\n\napp.use('*', (req, res) => {\n  res.sendFile(path.join(__dirname, 'build/index.html'));\n});\n\napp.listen(process.env.PORT || 8080);\n",
  'warningCount': 1}]
SublimeLinter: sublime_linter.py:507  Linting 'server.js' took 5.37s
```

The main difference, besides the warning about the missing file, being the `filePath` that gets outputted. I'm guessing this has something to do with the LintMatch update in the latest release but I don't know the Sublime Linter eco-system enough to contribute a solution.

**EDIT**: I could have sworn there were differences in the filePath output when I got 4.1.5 working last night, but I don't see any differences now. Probably was just imagining things. Regardless, 4.1.5 doesn't give errors about missing files and displays linting output on the code and 4.1.6 gives errors and displays nothing in the code, so there's something there.

**Comment by kaste** [comment]
Hm, thanks for reporting! 😢 

You're right with the `filePath` thingy. Now, your wsl eslint reports

```
'filePath': '/mnt/c/rails/tcg-website/C:railstcg-websiteserver.js',
```

Really, no slashes after the `C:`? How could we map that back to the filename you're actually editing right now?

'eslint.bat' is basically 'wsl eslint *', correct?

**Comment by kaste** [comment]
Hot-fix *could* be to set 'stdin-filename' to 'false' in the eslint section in the SL settings.

**Comment by TheStu** [comment]
Ya I tried messing with SL settings ...
```
"linters": {
    "eslint": {
      "@disable": false,
      "args": ["stdin-filename", "false"],
      "excludes": [],
      "executable": "C:\\rails\\eslint.bat"
    },
    ...
}
```
results in:
```
  C:\rails\tcg-website  (working dir)
  > type server.js | C:\rails\eslint.bat --format json --stdin stdin-filename false --stdin-filename C:\rails\tcg-website\server.js
```
and the same problem w/r/t missing files. And ya eslint.bat contains `wsl eslint %*`

**Comment by kaste** [comment]
Sl settings should look like 

```
"linters": {
    "eslint": {
      "disable": false,
      "stdin-filename": false",
      "excludes": [],
      "executable": "C:\\rails\\eslint.bat"
    },
    ...
}
```

This is more like a hack.

I still would like to know where this filename comes from. Technically it looks like someone does a `join(working_dir, filename)` but then somehow the slashes go away, and the joining doesn't recognize that filename is already an absolute path.

Can you reproduce on the command line? Does it come from the '.bat' file? Or the JSON reporter? Or the stdin-filename setting?

```
> wsl eslint C:\rails\tcg-website\server.js
> wsl eslint --format json C:\rails\tcg-website\server.js
> type C:\rails\tcg-website\server.js | wsl eslint --stdin-filename C:\rails\tcg-website\server.js
> type C:\rails\tcg-website\server.js | wsl eslint --format json --stdin-filename C:\rails\tcg-website\server.js
```

etc.

**Comment by TheStu** [comment]
ah okay yes, `"stdin-filename": false` does fix it :)
so I tried all the following:
```
C:\rails\tcg-website>wsl eslint server.js
C:\rails\tcg-website>wsl eslint server.js --format json
C:\rails\tcg-website>type server.js | wsl eslint --stdin --stdin-filename C:\rails\tcg-website\server.js
C:\rails\tcg-website>type server.js | wsl eslint --stdin --stdin-filename C:\rails\tcg-website\server.js --format json
C:\rails\tcg-website>type server.js | wsl eslint --stdin
```

**Comment by kaste** [comment]
Generally,

```
"linters": {
    "eslint": {
      ...
      "executable": ["wsl", "eslint"],
    },
    ...
}
```

*should* be better than doing the '.bat' dance, although 🤞 I'm not completely sure if you need to specify absolute paths here. (Pretty sure, Windows finds a 'wsl.exe' in your PATH, but I don't know how the second arg 'eslint' is resolved here.)

Escaping, ... well another way to 'escape/quote' things is probably to do `"--stdin-filename=C:\my path"`. This counts as one arg. (Basically `--foo bar` vs `--foo=bar`.) This is all a bit tricky, bc on Windows you would rather use `"`, on linux you would prefer `'` for quoting. 

E.g. 

```
>>> shlex.split(r"C:\rails\tcg-website\server.js")    # <== this is what you have
['C:railstcg-websiteserver.js']
>>> shlex.split(r"'C:\rails\tcg-website\server.js'")  # [1]
['C:\\rails\\tcg-website\\server.js']
```

[1] This is what you *should* get when you use `executable: ['wsl', 'eslint']`

**Comment by redblue9771** [comment]
I still have a bug. When the file location is modified, eslint will prompt that this directory or file does not exist. It is good after restarting VSCode.

![{$3 75RA9~J47UCU(8KT{4](https://user-images.githubusercontent.com/32461741/70619710-8c98b180-1c50-11ea-97c0-26019b0952fe.png)

**Comment by kaste** [comment]
A follow up issue is https://github.com/SublimeLinter/SublimeLinter/issues/1764

Generally, wsl is not supported.  From what I've tried it is also too slow.  I think, the recommended approach will be to install Sublime itself in the Linux container actually.
